version: '3'

services:
  spigot-server:
    container_name: spigot-server
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - INIT_MEMORY=1G
      - MAX_MEMORY=2G
      - EULA=false
      - OP=
    ports:
      - '25565:25565'
    volumes:
      - ./plugins:/usr/server/plugins
    networks:
      - minecraft-network

networks:
  minecraft-network:
    driver: bridge